# src/Stsbl/InternetBundle/Resources/config/legacy_aliases.yml
services:
    _defaults:
        autoconfigure: false
        autowire: false
        public: true

    stsbl.internet.nac_manager: '@Stsbl\InternetBundle\Service\NacManager'