# src/Stsbl/InternetBundle/Resources/config/services.yml
services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $connectionFactory: '@doctrine.dbal.connection_factory'

    Stsbl\InternetBundle\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Form/Data,Security}'

imports:
    - { resource: legacy_aliases.yml }