services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $connectionFactory: '@doctrine.dbal.connection_factory'

    Stsbl\InternetBundle\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Form/Data,Security}'
